apiVersion: v1
kind: Service
metadata:
  namespace: nginx-ns
  creationTimestamp: null
  labels:
    app: nginx-svc
  name: nginx-svc
spec:
  ports:
  - name: 80-80
    port: 80       #host port

    protocol: TCP
    targetPort: 80 #container port 
  selector:
    app: nginx
  type: ClusterIP
status:
  loadBalancer: {}
