apiVersion: v1
kind: Service
metadata:
  name: nginx-service-clusterip
  labels:
    env: demo
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  
    
  selector:
   
    app: nginx

